---
# Play-2: Bootstrap the first Node
- name: Bootstrap the first Node
  hosts: master
  become: true
  become_user: root
  vars_files:
    - vars.yml
  tasks:
    - name: Adding Nodes IPs
      ansible.builtin.lineinfile:
        path: /tmp/test.cfg
        regexp: '^wsrep_cluster_address=gcomm://'
        insertafter: 'wsrep_cluster_address=gcomm://'
        line: wsrep_cluster_address=gcomm://{{ cluster_hosts }}

    - name: Disable Traffic Encryption
      ansible.builtin.blockinfile:
        path: /tmp/test.cfg
        block: |
          # Disable Traffic Encryption
          pxc-encrypt-cluster-traffic=OFF


    - name: Display IP Address
      register: target_ip
      ansible.builtin.debug:
        var: ansible_default_ipv4.address


    - name: Set Node IP Address
      ansible.builtin.lineinfile:
        path: /tmp/test.cfg
        regexp: '^wsrep_node_address='
        line: wsrep_node_address={{ target_ip["ansible_default_ipv4.address"] }}


    - name: Set Cluster Name
      ansible.builtin.lineinfile:
        path: /tmp/test.cfg
        regexp: '^wsrep_cluster_name='
        line: wsrep_cluster_name={{ cluster_name }}


    - name: Comment WSREP node name to use node's hostname
      ansible.builtin.lineinfile:
        path: /tmp/test.cfg
        regexp: '^wsrep_node_name=pxc-n1'
        line: '# wsrep_node_name=pxc-n1'

    - name: Bootstrap the first node
      ansible.builtin.service:
        name: mysql@bootstrap
        state: started

